---
title: "2020 Data prep"
author: "Hardy Griesbauer"
date: "09/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(tidyverse)
library(here)
library(readxl)

```

## This document describes the steps used to clean and compile 2020 dataset for the offsite trial in the SBSmc2.

```{r define readData function,eval=FALSE}

# Define readData function

readData<-function(fname) {

x<-
  read_excel(here("data-raw/2020 data",fname), 
  sheet = "FieldCard", range=cell_cols("B:K")) 

# Extract some information from the spreadsheets
loc<-x[1,2] %>% as.character()
FID<-x[1,5] %>% as.character()  
xnames<-slice(x,n=3)
  


  x %>% 
  setNames(xnames) %>%  # set names
  slice(4:n()) %>% 

  # deal with plot numbers
  mutate(Plot=as.numeric(Plot)) %>%   
  fill(Plot) %>% 
  
  # set names
  setNames(c("Plot","Species","Seedlot","Condition_2019",
           "Condition_2020sp","Condition_2020fa","Height","Diameter","Leader",
           "Comment")) %>% 
  mutate(Measurement_Year=2020) %>% 
  mutate(FID=FID) %>% 
  mutate(Location=loc) %>% 
  dplyr::select(FID,Location,Plot:Condition_2020fa,Measurement_Year,
                Height:Comment) %>% 
    return()
  
} # close function

# read in seedlot information
seedlot<-
  read_csv(here("data-raw/seedlotData","Seedlot_info.csv")) %>% 
  mutate_all(factor) %>% 
  dplyr::select(-Species)


data2020<-
  list.files(here("data-raw/2020 data")) %>% 
  map_df(.,readData) %>% 
  mutate(FID=replace(FID,FID=="Frost","11_Frost")) %>% 
  mutate(FID=paste0("FID",FID)) %>% 
  mutate(Type=str_split(FID,pattern="_",n=2,simplify = T)[,2]) %>% 
  mutate(FID=str_split(FID,pattern="_",n=2,simplify = T)[,1]) %>%
  relocate(Type,.after="FID") %>% 
  mutate_at(vars(FID:Measurement_Year),factor) %>% 
  mutate(Condition_2020fa=fct_recode(Condition_2020fa,Good="good")) %>% 
  mutate(Condition_2020sp=fct_recode(Condition_2020sp,Missing="missing")) %>% 
  
  # reorder factor levels
  mutate(Condition_2020fa=fct_relevel(Condition_2020fa,"Missing","Dead","Moribund","Poor","Fair","Good")) %>% 
  mutate(Condition_2020sp=fct_relevel(Condition_2020sp,"Missing","Dead","Moribund","Poor","Fair","Good")) %>% 
  mutate(Condition_2019=fct_relevel(Condition_2019,"Missing","Dead","Moribund","Poor","Fair","Good")) %>% 
  
  # bring in seedlot information
  left_join(seedlot,by="Seedlot") %>% 
  relocate(Distance,.after="Seedlot") %>% 
  mutate(Distance=fct_relevel(Distance,"Local","Near","Far"))





save(data2020,file=here("data/2020_data","data2020.RData"))


```

## Read in 2020 data

```{r read 2020 data}

load(here("data/2020_data","data2020.RData"))

```

### Quick summaries
Let's see if the data are complete

```{r prelim look at data}

data2020 %>% 
  group_by(FID,Species,Seedlot) %>% 
  summarise(Num.Trees=n()) %>% 
  filter(Num.Trees!=36)


```

We can see that the frost FID has varying number of trees by species/seedlot.  Let's look into this a bit more.

```{r compare 2020 condition data to 2019 survival survey}

data2019_frost<-
  readxl::read_excel(here("data-raw/2019 survival survey/","SurvivalSurveyFID11Frost.xlsx"), 
    skip = 3) %>% 
  setNames(c("TreeID","Plot","Species","Seedlot","Condition","Comment")) %>% 
  mutate(Measurement_year="2019") %>% 
  fill(Plot:Seedlot)



```

